/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Colegio.Alumno;
import Colegio.Materia;
import java.util.HashSet;

/**
 *
 * @author ramir
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());
    
    public static HashSet<Alumno> listaAlumno = new HashSet<>();
    public static HashSet<Materia> listaMateria = new HashSet<>();
    
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAltaAlumno = new javax.swing.JMenu();
        jmiAltaAlumno = new javax.swing.JMenuItem();
        jmMateria = new javax.swing.JMenu();
        jmiAltaMateria = new javax.swing.JMenuItem();
        jmInscripcion = new javax.swing.JMenu();
        jmiInscripcion = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );

        jmAltaAlumno.setText("Alumno");

        jmiAltaAlumno.setText("Alta de Alumno");
        jmiAltaAlumno.addActionListener(this::jmiAltaAlumnoActionPerformed);
        jmAltaAlumno.add(jmiAltaAlumno);

        jMenuBar1.add(jmAltaAlumno);

        jmMateria.setText("Materia");

        jmiAltaMateria.setText("Alta de Materia");
        jmiAltaMateria.addActionListener(this::jmiAltaMateriaActionPerformed);
        jmMateria.add(jmiAltaMateria);

        jMenuBar1.add(jmMateria);

        jmInscripcion.setText("Inscripcion");

        jmiInscripcion.setText("Formulario de Inscripcion");
        jmiInscripcion.addActionListener(this::jmiInscripcionActionPerformed);
        jmInscripcion.add(jmiInscripcion);

        jMenuBar1.add(jmInscripcion);

        jmSalir.setText("Salir");

        jmiSalir.setText("Cerrar Ventana");
        jmiSalir.addActionListener(this::jmiSalirActionPerformed);
        jmSalir.add(jmiSalir);

        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAltaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAltaAlumnoActionPerformed
        VistaAlumnos va = new VistaAlumnos();
        escritorio.add(va);
        va.setVisible(true);
    }//GEN-LAST:event_jmiAltaAlumnoActionPerformed

    private void jmiAltaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAltaMateriaActionPerformed
       VistaMaterias vm= new VistaMaterias();
       escritorio.add(vm);
       vm.setVisible(true);
    }//GEN-LAST:event_jmiAltaMateriaActionPerformed

    private void jmiInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInscripcionActionPerformed
        VistaInscripcion va = new VistaInscripcion();
        escritorio.add(va);
        va.setVisible(true);
    }//GEN-LAST:event_jmiInscripcionActionPerformed

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmAltaAlumno;
    private javax.swing.JMenu jmInscripcion;
    private javax.swing.JMenu jmMateria;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jmiAltaAlumno;
    private javax.swing.JMenuItem jmiAltaMateria;
    private javax.swing.JMenuItem jmiInscripcion;
    private javax.swing.JMenuItem jmiSalir;
    // End of variables declaration//GEN-END:variables
}
